import domain from './domain'
export const GET_OPENID = 'https://tovinping.cn/api/common/getOpenId'
export const GET_UNIONID = 'https://tovinping.cn/api/common/getUnionid'
export const MATCH_UNIONID = domain + '/matchUnionId'
export const GET_VERCODE = domain + '/getVerCode'
export const BIND_UNIONID = domain + '/bindUnionId'
export const GET_TICKET = domain + '/getTicketByUserId'
export const DEL_TICKET = domain + '/delTicket'
export const GET_LIKE = domain + '/getLikeByUserId'
export const DEL_LIKE = domain + '/delLike'
export const GET_ADDRESS = domain + '/getAddressByUserId'
export const DEL_ADDRESS = domain + '/delAddress'
export const ADD_ADDRESS = domain + '/addAddress'
export const GET_MORETICKET = domain + '/getMoreTicket'
export const DEL_MORETICKET = domain + '/updateTicket'
export const REFRESHTOKEN = domain + '/refreshToken'